### ISSUE TITLE
Error in register coacher

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#19]
Page from FE: https://www.smesummit.id/coacher/

<img width="682" alt="screen shot 2018-12-29 at 14 09 54" src="https://user-images.githubusercontent.com/7221389/50534766-223c4d80-0b74-11e9-8dc6-65b55948b71b.png">

**Comment by ammarfaizi2** [comment]
Hello, I have fixed the coacher registration API in https://github.com/phpid-jakarta/api-smesummit.id-2019/pull/21

Here are the required fields:
```json
[
    "name",
    "company_name",
    "photo",
    "experience",
    "topic",
    "position",
    "company_sector",
    "last_education",
    "email",
    "phone",
    "captcha"
]
```

If you have any issue with this API, do not hesitate to contact me.

Thank you
