### ISSUE TITLE
Add field fb_link and ig_link in volunteer table

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#25]
Allow null for all table

**Comment by ammarfaizi2** [comment]
Hi, I have added the `fb_link` and `ig_link` field. You can just add them to the frontend post data fields. I'm sorry for the delay. I was really busy in my real life.

Don't close this issue until you have succeeded to implement this API to the frontend.

If you have any problem with this issue, please let me know, thanks.
