### ISSUE TITLE
Payment Instruction Status for Participants

### ISSUE THREAD

**Issue by hidayat365** [phpid-jakarta/api-smesummit.id-2019#34]
For easier process in backend, please use `status` field in `participants` table to update status after sending payment instruction. 

- Payment instruction should be sent only to participants with status of `null` or `New Request`. 
- Update status field to `Invoice Sent` after email successfully sent to participant

https://github.com/phpid-jakarta/api-smesummit.id-2019/blob/356c096e50f51740c56ef9b02f1f0aa22da20de3/cli/payment_instruction_mail.php#L49

**Comment by ammarfaizi2** [comment]
Hello, we have already been implemented this behavior, but with the different field name.

Ref https://github.com/phpid-jakarta/api-smesummit.id-2019/pull/32

`payment_instruction_email_sent` means that the user has already received the payment instruction.
https://github.com/phpid-jakarta/api-smesummit.id-2019/blob/20697fe45a804b90a06b218af13801bb35316cdc/database.sql#L60

**Comment by ammarfaizi2** [comment]
We don't need to discuss this issue anymore, so I close this issue. Thanks.
