### ISSUE TITLE
Add voucher redeeem api

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#35]
Based on om @hidayat365 comment:
----
jika memungkinkan proses registrasinya jadi begini
- peserta buka halaman registrasi
- peserta mengisi form registrasi
- peserta mengisi kode voucher, kmdn klik tombol [redeem]
- sistem akan memberitahukan apakah voucher masih valid
- jika voucher masih valid, maka di halaman registrasi akan ditampilkan nilai pembayaran sesudah diskon 
- peserta klik submit for registrasi

notes,
- kode voucher disimpan di field voucher_code di table participatns
- nilai pembayaran disimpan di field payment_amount di table participatns

**Comment by mazipan** [comment]
What we need to do

- [ ]  Add field `voucher` in participant table, allow null
- [ ]  Add table price and add active price that will used as base price for calculating voucher
- [ ]  Add new api for redeem voucher with rule above
- [ ]  field `voucher` only can save if voucher is valid when redemmed

**Comment by ammarfaizi2** [comment]
Hello, I have created the voucher API.

Here is the curl command

```shell
curl https://api.smesummit.id/participant_register.php?action=voucher \
--data '{"voucher": "QWE123"}' \
-H "Authorization: Bearer $token"
```

The `$token` is got from `https://api.smesummit.id/participant_register.php?action=get_token`

and here is the sample result

```json
{
    "status": "success",
    "data": {
        "before_discount": 500000,
        "after_discount": 400000,
        "description": "got discount 20%"
    }
}
```

To submit the voucher, please add a new field that named `voucher` when doing participant registration (https://api.smesummit.id/participant_register.php?action=submit)

Thank you.
