### ISSUE TITLE
Allowing cors from Dev Env

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#36]
Because Biznet can be down anytime, we need to activate dev environment as mirror for "plan b" when emergency needed.

Currently we already deploy to: https://smesummit.netlify.com/
But still facing cors when accessing API.
Need to whitelist this domain.

**Comment by ammarfaizi2** [comment]
When the Biznet Server is going down then the API will down also, so, there is no reason to use another mirror if we don't have the emergency server for the API.

Will we have an emergency server which served the same API?
