### ISSUE TITLE
Bugs in voucher redeemed API

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#37]

**Comment by mazipan** [comment]
- [  ] voucher with discount amount (not percentage) still not cut price
- [  ] voucher with status already redeemed still can be redeem
- [  ] voucher with inactive status should can not redeem

**Comment by ammarfaizi2** [comment]
Did I fix this bug?

**Comment by ammarfaizi2** [comment]
Didn't I fix this bug?
