### ISSUE TITLE
Deploy to server smesummit.id

### ISSUE THREAD

**Issue by mazipan** [phpid-jakarta/api-smesummit.id-2019#7]
Need to try to deploy to smesummit.id

**Comment by ammarfaizi2** [comment]
Since I don't have the root access, I can't deploy this project to the server. It should be done by om @peterjkambey or waiting for he gives it to us. We also need a subdomain to deploy this project together with User Interface.

I advise using `api.smesummit.id` for its subdomain.

**Comment by ammarfaizi2** [comment]
The root access has been granted and this API is now working properly.

**There are 2 examples that can be used to help the implementation of API in User Interface:**
- [Participant Register] https://api.smesummit.id/example_1.php
- [Volunteer Register] https://api.smesummit.id/example_2.php

I will finish the other APIs example and documentation soon.`

Please have a check from your end, do not hesitate to contact me or open an issue if there is any problem.

Thank You

**Comment by ammarfaizi2** [comment]
One more...

There is "Show Table" section that will show us the registered users. This section is available for every API.
![llll](https://user-images.githubusercontent.com/26004054/49879133-e149f680-fe5b-11e8-9c0a-ee7eb5f67561.png)

We can also reset the record for development purpose by clicking "Reset Table"
![vfvfv](https://user-images.githubusercontent.com/26004054/49879286-41d93380-fe5c-11e8-9c57-d898ab5f18d2.png)

**Comment by ammarfaizi2** [comment]
I just created the third example https://github.com/phpid-jakarta/api-smesummit.id-2019/pull/11
[Sponsor Register] https://api.smesummit.id/example_3.php

I will finish the other APIs example and documentation soon.`
